export const CREATE_SECTION_PENDING = 'sections/CREATE_SECTION_PENDING';
export const CREATE_SECTION_FULFILLED = 'sections/CREATE_SECTION_FULFILLED';
export const CREATE_SECTION_REJECTED = 'sections/CREATE_SECTION_REJECTED';

export const DELETE_SECTION_PENDING = 'sections/DELETE_SECTION_PENDING';
export const DELETE_SECTION_FULFILLED = 'sections/DELETE_SECTION_FULFILLED';
export const DELETE_SECTION_REJECTED = 'sections/DELETE_SECTION_REJECTED';

export const FETCH_SECTIONS_PENDING = 'sections/FETCH_SECTIONS_PENDING';
export const FETCH_SECTIONS_FULFILLED = 'sections/FETCH_SECTIONS_FULFILLED';
export const FETCH_SECTIONS_REJECTED = 'sections/FETCH_SECTIONS_REJECTED';