export const CREATE_ARTICLE_PENDING = 'articles/CREATE_ARTICLE_PENDING';
export const CREATE_ARTICLE_FULFILLED = 'articles/CREATE_ARTICLE_FULFILLED';
export const CREATE_ARTICLE_REJECTED = 'articles/CREATE_ARTICLE_REJECTED';

export const DELETE_ARTICLE_PENDING = 'articles/DELETE_ARTICLE_PENDING';
export const DELETE_ARTICLE_FULFILLED = 'articles/DELETE_ARTICLE_FULFILLED';
export const DELETE_ARTICLE_REJECTED = 'articles/DELETE_ARTICLE_REJECTED';

export const FETCH_ARTICLES_PENDING = 'articles/FETCH_ARTICLES_PENDING';
export const FETCH_ARTICLES_FULFILLED = 'articles/FETCH_ARTICLES_FULFILLED';
export const FETCH_ARTICLES_REJECTED = 'articles/FETCH_ARTICLES_REJECTED';

export const FETCH_AUTHORSHIPS_PENDING = 'articles/FETCH_AUTHORSHIPS_PENDING';
export const FETCH_AUTHORSHIPS_FULFILLED = 'articles/FETCH_AUTHORSHIPS_FULFILLED';
export const FETCH_AUTHORSHIPS_REJECTED = 'articles/FETCH_AUTHORSHIPS_REJECTED';