export const CREATE_ARTICLE_PENDING = 'articles/CREATE_ARTICLE_PENDING';
export const CREATE_ARTICLE_FULFILLED = 'articles/CREATE_ARTICLE_FULFILLED';
export const CREATE_ARTICLE_REJECTED = 'articles/CREATE_ARTICLE_REJECTED';

export const FETCH_ARTICLES_PENDING = 'articles/FETCH_ARTICLES_PENDING';
export const FETCH_ARTICLES_FULFILLED = 'articles/FETCH_ARTICLES_FULFILLED';
export const FETCH_ARTICLES_REJECTED = 'articles/FETCH_ARTICLES_REJECTED';