export const CREATE_ARTICLE_PENDING = 'articles/CREATE_ARTICLE_PENDING';
export const CREATE_ARTICLE_FULFILLED = 'articles/CREATE_ARTICLE_FULFILLED';
export const CREATE_ARTICLE_REJECTED = 'articles/CREATE_ARTICLE_REJECTED';