export const CREATE_USER_PENDING = 'users/CREATE_USER_PENDING';
export const CREATE_USER_FULFILLED = 'users/CREATE_USER_FULFILLED';
export const CREATE_USER_REJECTED = 'users/CREATE_USER_REJECTED';

export const DELETE_USER_PENDING = 'users/DELETE_USER_PENDING';
export const DELETE_USER_FULFILLED = 'users/DELETE_USER_FULFILLED';
export const DELETE_USER_REJECTED = 'users/DELETE_USER_REJECTED';

export const FETCH_USERS_PENDING = 'users/FETCH_USERS_PENDING';
export const FETCH_USERS_FULFILLED = 'users/FETCH_USERS_FULFILLED';
export const FETCH_USERS_REJECTED = 'users/FETCH_USERS_REJECTED';